spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sujithkumarmp/config-server-properties.git

server:
  port: ${CONFIGSERVER_PORT}

